### PR TITLE
Pakku auto update

### PR DESCRIPTION
**Pull request by hythm7**
* Auto update Pakku from main github branch.
although this will re-install `Pakku` every run, it's better than pulling updates manually.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
@Altai-man can you please review it? I haven't tried running Blin with Pakku lately, so you probably know better if this makes sense.

**Comment by Altai-man** [comment]
Hi. I did a run with Pakku soon after last release and it had some false positives reported.

This looks interesting, I will try to get to it next weekend.

**Comment by Altai-man** [comment]
```
➜  docker git:(master) ✗ ./dblin --nproc=24 --old=2020.10 --pm=pakku
Running Blin with parameters: --nproc=24 --old=2020.10 --pm=pakku
🥞 Installing Pakku
Already up to date.
Installing Pakku dependency [File::Directory::Tree]
Installing Pakku dependency [File::Temp]
Installing Pakku dependency [File::Find]
Installing Pakku dependency [Terminal::ANSIColor]
Installing Pakku dependency [Log::Async]
Installing Pakku dependency [JSON::Fast]
Installing Pakku dependency [URL]
Installing Pakku dependency [NativeLibs]
Installing Pakku dependency [LibCurl]
Installing Pakku dependency [Archive::Libarchive::Raw]
Installing Pakku dependency [NativeHelpers::Callback]
Installing Pakku dependency [Number::Bytes::Human]
Installing Pakku dependency [BitEnum]
Installing Pakku dependency [Libarchive]
Installing Pakku dependency [Retry]
Installing Pakku dependency [Pakku::Spec]
Installing Pakku dependency [Pakku::Meta]
Installing Pakku dependency [Pakku::RecMan::Client]
Installing Pakku...
🦋 PRC: ｢/mnt/data/pakku-src｣
🐞 SPC: ｢Pakku:auth<github:hythm7>:ver<pupa>:api<>｣
💀 MTA: ｢Pakku:auth<github:hythm7>:ver<pupa>:api<>｣
Nofun
The spawned command 'data/pakku/bin/pakku' exited unsuccessfully (exit code: 1, signal: 0)
  in sub MAIN at data/pakku-src/tools/install-pakku.raku line 100
  in block <unit> at data/pakku-src/tools/install-pakku.raku line 1

The spawned command 'data/pakku-src/tools/install-pakku.raku' exited unsuccessfully (exit code: 1, signal: 0)
  in submethod TWEAK at /mnt/lib/Blin/Tester/Pakku.rakumod (Blin::Tester::Pakku) line 23
  in sub MAIN at bin/blin.p6 line 41
  in block <unit> at bin/blin.p6 line 14
```
The result is as follows. @hythm7

**Comment by hythm7** [comment]
@Altai-man can you remove `data/pakku-src` and `data/pakku` directories and try again? I think its loading an older version of `Pakku::Meta` dependency.

**Comment by Altai-man** [comment]
@hythm7 it works after removal, checking another run. Sorry for the noise.

**Pull request merged**
